//LA PROPIEDAD TYPE DESCRIBE QUE DEBE CAMBIAR,Y EL PAYLOAD ES EL QUE , OSEA EL VALOR A LO QUE VA A CAMBIAR
//CON EL TYPE ENTIENDE QUE TIENE QUE HACER Y EL PAYLOAD ES ESA INFORMACION ADICIONAL QUE YO LE TENGO QUE ENVIAR AL REDUCER PARA QUE SEPA A QUE TIENE QUE CAMBIAR
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_DETAIL = "GET_DETAIL";
export const GET_NAME = "GET_NAME";
export const ORD_ALPHA = " ORD_ALPHA";
export const ORD_ALPHA_REV = " ORD_ALPHA_REV";
export const ORD_POP = "ORD_POP";
export const ORD_POP_REV = "ORD_POP_REV";
export const ORD_CONTINENT = "ORD_CONTINENT";
export const SHOW_ACTIV = "SHOW_ACTIV";